export const ADD_RECIPE = 'ADD_RECIPE'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const DELETE_ALL = 'DELETE_ALL'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'